### ISSUE TITLE
[Android] Développer l'Activity qui intègre la librairie OpenStreetMap

### ISSUE THREAD

**Issue by gotgot1995** [ISTIC-M2-ILa-GM/Projet-SIT-Groupe-2#4]
- [x] intégrer OpenStreetMap à une Activity
- [x] afficher des marqueurs sur la cartes
- [x] afficher les lignes entres les marqueurs
- [x] refactorer l'Activity en Fragment

**Comment by AdrienLeblanc** [comment]
Plus que la fragmentation à faire
