### ISSUE TITLE
[Spring] développer le contrôleur REST

### ISSUE THREAD

**Issue by gotgot1995** [ISTIC-M2-ILa-GM/Projet-SIT-Groupe-2#7]
List of endpoints:
- [x] GET /missions
- [x] POST /missions
- [x] GET /missions/{id}/positions
- [x] PATCH /missions/{id}/start
- [x] PATCH /missions/{id}/stop

**Comment by triggersch** [comment]
C'est fait !

**Comment by gotgot1995** [comment]
@triggersch et est-ce que ça s'intègre avec la partie MongoDB ?

**Comment by triggersch** [comment]
tout à fait
